#ifndef FORGE_GENERATOR_HPP
#define FORGE_GENERATOR_HPP

#include <string>
#include <vector>
#include "managers/SymbolTable.hpp"

namespace FORGE
{
    //! \brief An interface for any object that needs to generate code
    class Generator
    {
    public:

        //! \brief Request to get the ASM generated by the object that inherits this if
        //! \param symbol_table The table of symbols so the generation can pull any information required
        //!        to build its instruction set
        virtual std::vector<std::string> generate_NASM(SymbolTable & symbol_table) = 0;
    };
}

#endif