#ifndef FORGE_GENERATOR_HPP
#define FORGE_GENERATOR_HPP

#include <string>
#include <vector>
#include "managers/SymbolTable.hpp"
#include "codegen/Codegen.hpp"

namespace FORGE
{
    //! \brief An interface for any object that needs to generate code
    class GeneratorIf
    {
    public:

        //! \brief Request to get the ASM generated by the object that inherits this if
        //! \param code_gen The generator they will use to generate NASM
        virtual void generate_NASM(Codegen & code_gen) = 0;
    };
}

#endif